/**
* A Node that is belongs to a doubly linked list. Created by Chami Lamelas.
* 		
* Known Bugs: None
*
* @author Xiao Wanyue
* xwanyue@brandeis.edu
* Oct 7, 2021
* COSI 21A PA1
*/
package main;

/**
 * Doubly linked list node - DO NOT EDIT THIS FILE.
 * 
 * @author Chami Lamelas
 *
 */
public class Node {
	
	public Node next;
	public Node prev;
	public char data;
	
	public Node(char c) {
		this.next = null;
		this.prev = null;
		this.data = c;
	}
}
